"""add or adjutsment table health and checkup

Revision ID: 4cbe1fbd781c
Revises: a5d8d3d2b7d9
Create Date: 2023-09-10 22:53:06.680060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4cbe1fbd781c'
down_revision = 'a5d8d3d2b7d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkup_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=False),
    sa.Column('doctor_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('ai_result_health_data_fkey', 'ai_result', type_='foreignkey')
    op.drop_column('ai_result', 'health_data')
    op.add_column('health_data', sa.Column('title', sa.String(), nullable=False))
    op.add_column('health_data', sa.Column('color', sa.String(), nullable=True))
    op.add_column('health_data', sa.Column('value', sa.Integer(), nullable=False))
    op.drop_column('health_data', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_data', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('health_data', 'value')
    op.drop_column('health_data', 'color')
    op.drop_column('health_data', 'title')
    op.add_column('ai_result', sa.Column('health_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('ai_result_health_data_fkey', 'ai_result', 'health_data', ['health_data'], ['id'])
    op.drop_table('checkup_history')
    # ### end Alembic commands ###
