"""add prevention table

Revision ID: 53d800c8ab2f
Revises: 4cbe1fbd781c
Create Date: 2023-09-11 13:50:27.700991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d800c8ab2f'
down_revision = '4cbe1fbd781c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prevention',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ai_result', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prevention')
    # ### end Alembic commands ###
