"""add healt_data_id in airesult

Revision ID: a5d8d3d2b7d9
Revises: a2a1b6c47409
Create Date: 2023-09-07 16:40:24.571481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d8d3d2b7d9'
down_revision = 'a2a1b6c47409'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_result', sa.Column('health_data', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ai_result', 'health_data', ['health_data'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_result', type_='foreignkey')
    op.drop_column('ai_result', 'health_data')
    # ### end Alembic commands ###
